package internal

import (
	"errors"
	"io"

	"github.com/grafov/m3u8"
)

// GetURIFromM3U8 returns uri generated by parsing m3u8.
func GetURIFromM3U8(input io.Reader) (string, error) {
	playlist, listType, err := m3u8.DecodeFrom(input, true)
	if err != nil || listType != m3u8.MASTER {
		return "", err
	}
	p := playlist.(*m3u8.MasterPlaylist)

	if p == nil || len(p.Variants) != 1 || p.Variants[0] == nil {
		return "", errors.New("invalid m3u8 format")
	}
	return p.Variants[0].URI, nil
}
